In [39]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [42]:
data = np.loadtxt('./datasets/data.txt')
covar = np.cov(data.T)
eig_vectors= np.linalg.eig(covar)[1]
u_red= eig_vectors[:,:2]
reduced=np.dot(data,u_red)
plt.scatter(reduced[:,0], reduced[:,1]) 
plt.show()

In [12]:

model = PCA(n_components=99)
# model.fit(data[:,:-1])
print(model.fit(data[:,:-1]))
print(model.explained_variance_)

# data = model.fit_transform(data[:,:-1],data[:,-1])

# plt.scatter(data[:,0],data[:,1])
# plt.show()

PCA(copy=True, iterated_power='auto', n_components=99, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)
[9.00568317e+00 4.45097308e+00 5.18610411e-03 5.03208903e-03
 4.91323622e-03 4.71250995e-03 4.63673477e-03 4.49190637e-03
 4.45884069e-03 4.30599536e-03 4.23504641e-03 4.18627778e-03
 4.15068897e-03 4.09078142e-03 3.94104595e-03 3.91226867e-03
 3.84725272e-03 3.75161946e-03 3.71346131e-03 3.63610979e-03
 3.61558602e-03 3.56618650e-03 3.48445146e-03 3.45399639e-03
 3.40574119e-03 3.33764023e-03 3.30640342e-03 3.29450601e-03
 3.22201990e-03 3.19671352e-03 3.16167088e-03 3.09024576e-03
 2.99882605e-03 2.98458043e-03 2.92573113e-03 2.88142461e-03
 2.84765853e-03 2.77693841e-03 2.76573941e-03 2.73470101e-03
 2.69315814e-03 2.65237221e-03 2.64370464e-03 2.58117251e-03
 2.53954242e-03 2.51843035e-03 2.42323072e-03 2.41213312e-03
 2.36215119e-03 2.34198175e-03 2.30547872e-03 2.22043699e-03
 2.21053701e-03 2.19285648e-03 2.15624792e-03 2.11679780e-03
 2.11097173e-03 2.07919352e-

In [34]:
w = np.random.randint(low=0, high=2, size=[2,4])
print(w)
x = np.random.randint(low=0, high=2, size=[4,3])
print(x)

[[1 1 1 1]
 [0 0 1 0]]
[[1 1 0]
 [1 0 0]
 [0 0 0]
 [0 0 1]]


In [35]:
print(np.dot(w,x))

[[2 1 1]
 [0 0 0]]
